# Include a color scheme file
include colors.conf

# Font settings
font_family GeistMono Nerd Font
font_size 10

# Ligatures and audio
disable_ligatures never
enable_audio_bell no

# Shell settings
shell zsh
shell_integration no-cursor

# Cursor
cursor_shape block

# URL highlighting
url_color white
url_style curly

# Window behavior
remember_window_size no
background_opacity 0.50
sync_to_monitor no
