#!/home/arch12/.local/share/pipx/venvs/pywalfox/bin/python
import sys
from pywalfox.__main__ import main
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
